### ISSUE TITLE
Be compatible with other corona app systems

### ISSUE THREAD

**Issue by Thaodan** [THLfi/koronavilkku-backend#18]
Have you thought of making the infrastructure compatible with the infrastructure that was setup of by other countries like Germany in [corona-warn-app/cwa-server](https://github.com/corona-warn-app/cwa-server)?

That would not need to use the same server but just the same software or protocol.
Currently their are foss apps such as [llewelld/harbour-contrac](https://github.com/llewelld/harbour-contrac) that want implement a compatible app for such systems but its hard to implement a backend for every service. 

Also it feels needlessly complicated as the Google/Apple spec that is used to parse the data is the same across almost all apps.

**Comment by samikki** [comment]
The backend interoperability between countries is being designed on EU-level and we are following that project closely. Decisions regarding that will be made in the near future.

**Comment by Thaodan** [comment]
Its not about interoperability only but about reducing the cost of maintenance and making the servers more accessible.
