### ISSUE TITLE
need prerequisites for tools

### ISSUE THREAD

**Issue by ikke-t** [THLfi/koronavilkku-backend#7]
As a RHEL8 user I can not build the backend.

I went through the needed packages, and will update the README.

Let's add section for prerequisites.

**Comment by ikke-t** [comment]
This is basically this:

```
sudo dnf install java-11-openjdk-devel java-11-openjdk
sudo alternatives --config java
sudo alternatives --config jre_openjdk
sudo alternatives --config java_sdk_openjdk
sudo alternatives --config javac
```

perhaps better yet to do the whole build in a container. I'll see how  to get that done.

**Comment by solita-alperttiti** [comment]
Firstly, I apologize that our answer has been lasted so long. Anyway, I think instructions about how to install correct version of java in different environments is out of scope of project's readme.

However, I think the idea of instructions for containerized build is great. One way to achieve this is by using maven docker image from docker hub: https://hub.docker.com/_/maven

If you have docker installed then you can build the koronavilkku-backend by running something like this:

`docker run -it --rm --name koronavilkku-backend -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.3-openjdk-11 mvn clean package`

It would be great if you could create a fine tuned instructions for containerized build and create a pull request for it. We can then merge it into official readme. How does this sound to you?

**Comment by ikke-t** [comment]
No problems, I have been too busy to look at any GitHub stuff in the last couple of weeks. I can take a shot at it at some point. I actually was thinking of using the java s2i images, and took it a bit further and configured OpenShift to do it for me.

That is actually all implemented and documented in here: https://github.com/ikke-t/koronavilkku-backend/tree/openshift-guide/openshift

I can make a PR for that if you see that fit for your purpose. It takes the code git url, and uses s2i images to build an image from the source code. It also uploads it to registry.

The build part would be also trivial using that image under podman. But I can't work on this this week.

As a personal note, [s2i image is this](https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4), built from [this](https://github.com/jboss-container-images/openjdk)

**Comment by solita-alperttiti** [comment]
I checked this out briefly and it seems very promising. I believe we would like to take it in a someway or another. Which in practice means at least linking to your repo if it's ok for you. However, this still needs some discussions in our end what the actual model could be from our perspective (in main repo, own repo for this, linking, or something else). I'll get back into this matter asap after I'll know more.

**Comment by ikke-t** [comment]
koronavilkku-ocp might be worth it's own repo. OCP stands for OpenShift Container Platform. The setup is very rudimentary basics, but it works.

**Comment by solita-alperttiti** [comment]
It seems that we're not going to do this at least now. So, I'll close this issue. Thank you for your efforts and let's re-open or create a new one if things are changing in the future.
